### PR TITLE
fixed Issue 2 (ot_curr_dist > remaining miles)

### PR DESCRIPTION
**Pull request by hughamacmullaniv**

### CODE REVIEW

**Comment by mdroste** [comment]
I agree with your proposal, and thanks for taking the initiative to submit changes! 

I must add that since I am from the upper midwest, I know a little bit about your name, and I'm quite amused and honored to have gotten your attention with this implementation of Oregon Trail. I suppose after the last 10 months, we're all looking for simple things :)

**Comment by hughamacmullaniv** [comment]
Indeed! Working in my attic all day, I try to spend a bit of time shaving the yak here and there, so it's not just the Same Old Thing. Glad to help keep the wagons rollin'!

Congratulations on being in the Stata News v36 no1 today!!

That said: I'm not sure what about my name might be famous (infamous? 😄) in the upper Midwest. I _was_ the US Orienteering champion twice, when I was 14 & 17, but I doubt that's it. 😆

**Comment by mdroste** [comment]
Lol! There is a Cargill heir with a nearly identical name, including IV. More common than it appears, I guess. :)

Big fan of WRDS over here though!

**Comment by mdroste** [comment]
Cool to see a swarthmore local on here as well - graduated from there in 2014!

**Comment by hughamacmullaniv** [comment]
Ohh, hah, I wish! _Those_ MacMillans! I wonder what I'd be doing if I were. I like to think it would still involve noodling around with code on occasion.

No kidding, Swat?!? What a small world. Stay well, Michael. If you get a job at Wharton, look me up. I support faculty research!

**Pull request merged**
